version: "3.9"

services:
  backend:
    build: ./node
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./node/.env
    volumes:
      - ./node:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prestamos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge

